// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY--Qza7EYWsG0R5kFjsIY6m9-Pj4C95g',
    appId: '1:402921769540:web:7040f54bd7fcccd2c38a11',
    messagingSenderId: '402921769540',
    projectId: 'khola-394f4',
    authDomain: 'khola-394f4.firebaseapp.com',
    storageBucket: 'khola-394f4.firebasestorage.app',
    measurementId: 'G-HR85XH9SQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0dfgEhC4mY_v1oQE98fX4GmylNgWWCfQ',
    appId: '1:402921769540:android:23ba69f0f34d1453c38a11',
    messagingSenderId: '402921769540',
    projectId: 'khola-394f4',
    storageBucket: 'khola-394f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2wxkMd4URBBYoitm4w4U9yVNfXf5nq5o',
    appId: '1:402921769540:ios:a6f493ae02fc5a3ec38a11',
    messagingSenderId: '402921769540',
    projectId: 'khola-394f4',
    storageBucket: 'khola-394f4.firebasestorage.app',
    iosBundleId: 'com.example.civicspot',
  );
}
